### PR TITLE
deleted instructions for no reason

### PR DESCRIPTION
**Pull request by jalletto**
Hi, @gmmowry! I hope I did this right.

### CODE REVIEW

**Comment by gmmowry** [comment]
Hi! When you get into the work place, best practice is to wait to merge a branch into master until you've received the :shipit: from another developer, a senior engineer, your boss, etc. so they have a chance to review the code and ensure it won’t break anything. Just to keep in mind for the future! Looks good! :shipit:

**Comment by jalletto** [comment]
Thanks Glenna!

Jus to clarify, I understand that in a professional setting I would not be
doing the merging, but for the rest of phase zero should I do it myself?

Best.

Josh

**Comment by gmmowry** [comment]
Yep! You can do all of the merging in your own phase 0 tracks repo. Merging is different in professional settings, sometimes you'd be waiting on a code review and then you could merge, or sometimes someone else would be doing the merging. Depends on the team and their work flow!

**Comment by jalletto** [comment]
Great. Thanks so much!

**Pull request merged**
